clusterName: document-service-eks-cluster
region: us-east-1
vpcId: "vpc-04b375ef3a12eb4d4"

serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    "eks.amazonaws.com/role-arn": "arn:aws:iam::306024784101:role/alb-controller-role"
