# yaml-language-server: $schema=../../../lite-ci/schemas/component.schema.yaml
apiVersion: sourceplane.io/v1
kind: Component

metadata:
  name: document-service-infra

spec:
  type: terraform
  domain: platform
  subscribe:
    environments:
      - dev
  labels:
    team: platform
    layer: service
  dependsOn:
    - component: eks
      scope: same-environment
      condition: success
