# yaml-language-server: $schema=../../../lite-ci/schemas/component.schema.yaml
apiVersion: sourceplane.io/v1
kind: Component

metadata:
  name: eks

spec:
  type: terraform
  domain: platform
  subscribe:
    environments:
      - dev
  labels:
    team: platform
    layer: compute
  dependsOn:
    - component: vpc
      scope: same-environment
      condition: success
